### ISSUE TITLE
请问如何在action同时执行多个账号？

### ISSUE THREAD

**Issue by log2cn** [Do1e/NJU_Health-Checkin#28]

**Comment by Do1e** [comment]
在secret中自行设置两个账号密码，如`STUDENT_ID1`、`STUDENT_ID2`、`PASSWORD1`、`PASSWORD2`，在`mian.yml`中添加需要运行的步骤，如：
```yaml
- name: Run
  env:
    STUDENT_ID: ${{ secrets.STUDENT_ID1 }}
    PASSWORD: ${{ secrets.PASSWORD1 }}
    USER_AGENT: ${{ secrets.USER_AGENT }}
    LOCATION: ${{ secrets.LOCATION }}
    BODY_TEMP_OK: ${{ secrets.BODY_TEMP_OK }}
    HEALTH_STATUS: ${{ secrets.HEALTH_STATUS }}
    MY_HEALTH_CODE_COLOR: ${{ secrets.MY_HEALTH_CODE_COLOR }}
    FAM_MEM_HEALTH_CODE_COLOR: ${{ secrets.FAM_MEM_HEALTH_CODE_COLOR }}
    LAST_RNA: ${{ secrets.LAST_RNA }}
    TRY_N_TIMES: ${{ secrets.TRY_N_TIMES }}
    LEAVE_NJ: ${{ secrets.LEAVE_NJ }}
  run: python decodeEnv.py && python checkin.py
- name: Run
  env:
    STUDENT_ID: ${{ secrets.STUDENT_ID2 }}
    PASSWORD: ${{ secrets.PASSWORD2 }}
    USER_AGENT: ${{ secrets.USER_AGENT }}
    LOCATION: ${{ secrets.LOCATION }}
    BODY_TEMP_OK: ${{ secrets.BODY_TEMP_OK }}
    HEALTH_STATUS: ${{ secrets.HEALTH_STATUS }}
    MY_HEALTH_CODE_COLOR: ${{ secrets.MY_HEALTH_CODE_COLOR }}
    FAM_MEM_HEALTH_CODE_COLOR: ${{ secrets.FAM_MEM_HEALTH_CODE_COLOR }}
    LAST_RNA: ${{ secrets.LAST_RNA }}
    TRY_N_TIMES: ${{ secrets.TRY_N_TIMES }}
    LEAVE_NJ: ${{ secrets.LEAVE_NJ }}
  run: python decodeEnv.py && python checkin.py
```

配置文件选择是方便本地运行的。
